name: core
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  dio: ^5.4.3+1
  get_it: ^7.6.8
  pretty_dio_logger: ^1.3.1

  domain:
    path: ../domain
  data:
    path: ../data
  flutter_secure_storage: ^4.2.1
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
