name: domain
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1

  data:
    path: ../data


dev_dependencies:
  build_runner: ^2.4.9
  lints: ^2.1.0
  test: ^1.24.0
